//
//  LockerModels.swift
//  Cync
//
//  The physical locker layout — one cell per row/col slot inside a named
//  zone (e.g. "B201", "B203(1)") — generated by
//  `scripts/generate_lockers.py` into `lockers.json` and loaded via
//  `LockerDataLoader`. That JSON only carries zoneId/row/col/lockerNumber;
//  `LockerCell.status` starts at `.unknown` and is filled in afterwards by
//  matching `LockerAPIService`'s server data onto cells by `lockerNumber`
//  (see `LockerMapViewController.applyStatuses`). Distinct from
//  `Locker.swift`, which is the server-backed `GET /api/lockers` rental
//  record itself.
//

import Foundation

/// Named `LockerCellStatus`, not `LockerStatus` — that name is already
/// taken by `Locker.swift`'s server-backed rental status. Mirrors that
/// enum's cases (`LockerAPIService` maps one to the other) plus three
/// states `Locker.swift` has no need for: `unknown` (this cell's
/// `lockerNumber` had no match in the server response), `reserved` (no
/// `lockerNumber` at all — e.g. B206's 학생회 사물함 columns — never sent to
/// the server, always shown as "-"), and `selected` (a purely local UI
/// state — e.g. highlighting a tapped cell — never set from the server).
enum LockerCellStatus: String, Codable {
    case empty      // server: AVAILABLE
    case pending    // server: PENDING
    case occupied   // server: IN_USE
    case broken     // server: BROKEN
    case unknown
    case reserved
    case selected
}

struct LockerCell: Identifiable, Codable {
    var id: String { "\(zoneId)_\(row)_\(col)" }
    let zoneId: String
    let row: Int
    let col: Int
    /// `nil` for a reserved slot (see `LockerCellStatus.reserved`) — it has
    /// no rental number and is displayed as "-" instead.
    let lockerNumber: Int?
    var status: LockerCellStatus
}

struct LockerZone: Identifiable, Codable {
    var id: String { zoneId }
    let zoneId: String
    let cells: [LockerCell]
}
