//
//  LockerDataLoader.swift
//  Cync
//
//  Loads the bundled `lockers.json` (the physical layout generated by
//  `scripts/generate_lockers.py`) and groups its flat cell list by
//  `zoneId` for the locker grid screens to render zone by zone.
//
//  `lockers.json` only carries layout fields (zoneId/row/col/lockerNumber)
//  — it has no `status`. A cell with `lockerNumber: null` is reserved
//  (e.g. B206's 학생회 사물함 columns) and starts at `.reserved`; every other
//  cell starts at `.unknown` — real status comes from the server
//  afterwards (see `LockerAPIService`), never from this file.
//

import Foundation

/// The shape actually stored in `lockers.json` — layout only, no status.
private struct LockerCellLayout: Decodable {
    let zoneId: String
    let row: Int
    let col: Int
    let lockerNumber: Int?
}

enum LockerDataError: LocalizedError {
    case fileNotFound(String)
    case unreadable(Error)
    case decoding(Error)

    var errorDescription: String? {
        switch self {
        case .fileNotFound(let name):
            return String(appLocalized: .lockerDataFileNotFound(name))
        case .unreadable:
            return String(appLocalized: .lockerDataUnreadable)
        case .decoding:
            return String(appLocalized: .lockerDataInvalid)
        }
    }
}

enum LockerDataLoader {
    /// Loads `resource.json` from `bundle` and groups its cells by `zoneId`.
    static func loadGroupedByZone(
        resource: String = "lockers",
        bundle: Bundle = .main
    ) throws -> [String: [LockerCell]] {
        guard let url = bundle.url(forResource: resource, withExtension: "json") else {
            throw LockerDataError.fileNotFound(resource)
        }

        let data: Data
        do {
            data = try Data(contentsOf: url)
        } catch {
            throw LockerDataError.unreadable(error)
        }

        let layouts: [LockerCellLayout]
        do {
            layouts = try JSONDecoder().decode([LockerCellLayout].self, from: data)
        } catch {
            throw LockerDataError.decoding(error)
        }

        let cells = layouts.map { layout in
            LockerCell(
                zoneId: layout.zoneId,
                row: layout.row,
                col: layout.col,
                lockerNumber: layout.lockerNumber,
                status: layout.lockerNumber == nil ? .reserved : .unknown
            )
        }

        return Dictionary(grouping: cells, by: \.zoneId)
    }
}
